### ISSUE TITLE
平方根計算の時に右のウィンドウが有効化されている

### ISSUE THREAD

**Issue by xiao621** [tsuu32/git-enpit-training-201906#5]
## 操作手順
* 8 √ 3 小数点以下そのまま
* 2.83842712474619

## 本来の想定
* 演算子√を選ぶ
* 右のウィンドウは無効化

## 操作環境
* OS
* OSバージョン
* Safari
* ブラウザバージョン

**Comment by tsuu32** [comment]
いいですね

**Comment by tsuu32** [comment]
fixed by #8
